<a href="https://colab.research.google.com/github/MoronSlayer/Deep-Learning-Projects/blob/learner/541_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
df = pd.read_csv("ratings.csv")
df.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [3]:
max(df['userId']),max(df['movieId'])

(610, 193609)

In [4]:
n = len(pd.unique(df['userId']))
m = len(pd.unique(df['movieId']))
print("No.of.unique user :", n)
print("No.of.unique movies :", m)

No.of.unique user : 610
No.of.unique movies : 9724


In [7]:
!pip install RAPIDS

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
ratings_matrix = np.zeros((610, 9724)) # matrix of size n users x p movies

In [6]:
sparseMatrix = csr_matrix((610, 193609), dtype = np.int8).toarray()

In [9]:
ratings_matrix.shape

(610, 9724)

In [ ]:
index_list = dict()
for df['userId'] 

In [ ]:
index = map(lambda x: df[''])

In [12]:
users = df['userId'].unique().tolist()
movies = df['movieId'].unique().tolist()

In [20]:
len(users),len(movies)

(610, 9724)

In [17]:
for i in range(len(df)):
  u = df['userId'][i]
  u = users.index(u)
  m = df['movieId'][i]
  m = movies.index(m)

  ratings_matrix[u][m] = df['rating'][i]


In [18]:
ratings_matrix

array([[4. , 4. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 0. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 5. , ..., 3. , 3.5, 3.5]])

In [19]:
movies[3]

47

In [21]:
data = df.copy()

In [22]:
for i in range(len(data)):
  u = data['userId'][i]
  u = users.index(u)
  m = data['movieId'][i]
  m = movies.index(m)

  data['userId'][i] = u
  data['movieId'][i] = m

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [24]:
data = data.drop(columns = ['rating', 'timestamp'])

In [28]:
indexes = data.values

In [35]:
data

userId  movieId
0            0        0
1            0        1
2            0        2
3            0        3
4            0        4
...        ...      ...
100831     609     3120
100832     609     2035
100833     609     3121
100834     609     1392
100835     609     2873

[100836 rows x 2 columns]

In [26]:
df

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [27]:
movies[3120]

166534

In [29]:
indexes

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [ 609, 3121],
       [ 609, 1392],
       [ 609, 2873]])

In [33]:
from sklearn.model_selection import train_test_split

training, test = train_test_split(indexes,train_size = 0.9 )

In [39]:
u = np.random.normal((2, 10))

In [41]:
def func(X, epochs, lr, lam):
  u = np.random.normal((len(ratings_matrix), 10))
  v = np.random.normal((10, len(ratings_matrix[0])))

  for e in epochs:
    sum = 0
    for i in X:
      d = np.dot(u[i[0]], v)
      l = (ratings_matrix[v[0]][v[1]] - d)**2
      norm = 0.5*lam*(np.linalg.norm(u) + np.linalg.norm(v))
      loss = 0.5*l + norm

    

    print(loss)

    u = u - lr* np.gradient(u)
    v = v - lr* np.gradient(u)




In [ ]:
fun()

In [43]:
test

array([[ 270, 1448],
       [ 386, 1210],
       [  39,  312],
       ...,
       [ 103, 1255],
       [ 185,  161],
       [ 140,  728]])

In [45]:
ratings_matrix[test]

IndexError: ignored